//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string To_ { get; set; }
        public Nullable<int> From_ { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<bool> ReadStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
