//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadComment
    {
        public int Id { get; set; }
        public Nullable<int> UploadID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Comment { get; set; }
    
        public virtual Upload Upload { get; set; }
    }
}
